CREATE TABLE BODBA.BO_ZONASXCOMUNA_VENTA_MASIVA(
   ZVM_ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
   ZVM_ID_COMUNA INTEGER not null,
   ZVM_ID_ZONA INTEGER,
   CONSTRAINT PK_ZVM_ID PRIMARY KEY (ZVM_ID)
) IN BO_TABLESPACE
GO

COMMENT ON TABLE BODBA.BO_ZONASXCOMUNA_VENTA_MASIVA IS 'ENLACE DE ZONAS CON COMUNAS PARA VENTAS MASIVAS'
GO
COMMENT ON COLUMN BODBA.BO_ZONASXCOMUNA_VENTA_MASIVA.ZVM_ID IS 'Id unico de la tabla.'
GO
COMMENT ON COLUMN BODBA.BO_ZONASXCOMUNA_VENTA_MASIVA.ZVM_ID_COMUNA IS 'Id de comuna'
GO
COMMENT ON COLUMN BODBA.BO_ZONASXCOMUNA_VENTA_MASIVA.ZVM_ID_ZONA IS 'Id de Zona'
GO