--Para registar op y token de pago asociado a venta masiva
CREATE TABLE BODBA.BO_VENTAMASIVA_PURCHASE(
   ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
   ID_PEDIDO INTEGER not null,
   TOKEN_PAGO VARCHAR (255),
   ESTADO CHAR(1),
   FCREACION  TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP,
   FVALIDACION  TIMESTAMP,
   CONSTRAINT PK_PAGO_ID PRIMARY KEY (ID)
) IN BO_TABLESPACE
GO

COMMENT ON TABLE BODBA.BO_VENTAMASIVA_PURCHASE IS 'Registro de pago en a traves de la App Venta Masiva.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.ID IS 'Id unico de la tabla.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.ID_PEDIDO IS 'Numero de pedido.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.TOKEN_PAGO IS 'Hash para validar op post ejecucion del servicio de pago seleccionado.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.ESTADO IS 'Estado de pago A: aceptado, R: rechazado.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.FCREACION IS 'Fecha creacion token de validacion.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.FVALIDACION IS 'Fecha en que se valido el pago. (Cuando cambia el estado)';

-- localhost:9080 ***
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'URL_PAGO_CAT_TBRAINS', 'https://pagos.tarjetasmas.cl/BotonDePagoCencosud/inicio.do' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_TBRAINS', 'http://10.95.6.109:9080/VentaMasiva/PurchasePay' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_BASE_TBRAINS', 'http://10.95.6.109:9080' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_SUCCESS_TBRAINS', 'http://10.95.6.109:9080/VentaMasiva/app/success.html' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_ERROR_TBRAINS', 'http://10.95.6.109:9080/VentaMasiva/app/error/error.html' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'POLIGONO_VENTA_MASIVA', '206' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'VALOR_MINIMO_DESPACHO_VENTA_MASIVA', '6990' FROM BODBA.BO_PARAMETROS
GO

-- ALMENDRO DMZ
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'URL_PAGO_CAT_TBRAINS', 'https://pagos.tarjetasmas.cl/BotonDePagoCencosud/inicio.do' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_TBRAINS', 'http://172.18.145.62/VentaMasiva/PurchasePay' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_BASE_TBRAINS', 'http://172.18.145.62' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_SUCCESS_TBRAINS', 'http://172.18.145.62/VentaMasiva/app/success.html' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_ERROR_TBRAINS', 'http://172.18.145.62/VentaMasiva/app/error/error.html' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'POLIGONO_VENTA_MASIVA', '206' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'VALOR_MINIMO_DESPACHO_VENTA_MASIVA', '6990' FROM BODBA.BO_PARAMETROS
GO


-- PUBLICA 
--Responsive:   http://pagostest.tarjetasmas.cl/BotonDePagoTA/inicio.do
--NO Responsive:https://pagos.tarjetasmas.cl/BotonDePagoCencosud/inicio.do
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'URL_PAGO_CAT_TBRAINS', 'http://pagostest.tarjetasmas.cl/BotonDePagoTA/inicio.do' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_TBRAINS', 'http://200.1.131.54/VentaMasiva/PurchasePay' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_BASE_TBRAINS', 'http://200.1.131.54' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_SUCCESS_TBRAINS', 'http://jumbobf-front.dev.2brains.cl/#/success' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'o', 'http://jumbobf-front.dev.2brains.cl/#/error' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'POLIGONO_VENTA_MASIVA', '206' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'VALOR_MINIMO_DESPACHO_VENTA_MASIVA', '6990' FROM BODBA.BO_PARAMETROS
GO

-- Generacion de zona de Venta masiva para calendario
INSERT INTO BODBA.BO_ZONAS(ID_LOCAL, NOMBRE, DESCRIPCION, TARIFA_NORMAL_BAJA, TARIFA_NORMAL_MEDIA, TARIFA_NORMAL_ALTA, TARIFA_ECONOMICA, TARIFA_EXPRESS, ESTADO_TARIFA_EXPRESS, ESTADO_TARIFA_ECONOMICA, MENSAJE_CAL_DESPACHO, ORDEN_ZONA, REGALO_CLIENTES, ESTADO_DESCUENTO_CAT, ESTADO_DESCUENTO_TBK, ESTADO_DESCUENTO_PAR, MONTO_DESCUENTO_CAT, MONTO_DESCUENTO_TBK, MONTO_DESCUENTO_PAR, MONTO_DESCUENTO_PC_CAT, MONTO_DESCUENTO_PC_TBK, MONTO_DESCUENTO_PC_PAR) 
	VALUES(1, 'Z99 Venta Masiva', 'Venta Masiva', 990, 990, 990, 990, 990, 0, 0, '', 1000, 1, 3, 3, 3, 120000, 120000, 120000, 50000, 50000, 50000)
GO
INSERT INTO BODBA.BO_POLIGONO(ID_ZONA, ID_COMUNA, NUM_POLIGONO, DESCRIPCION) 
	VALUES( 644, 2, 0, 'Poligono Venta Masiva')
GO

--delete from BODBA.BO_PARAMETROS where NOMBRE='URL_PAGO_CAT_TBRAINS'
--delete from BODBA.BO_PARAMETROS where NOMBRE='REDIRECT_URL_PAYMENT_TBRAINS'
--delete from BODBA.BO_PARAMETROS where NOMBRE='REDIRECT_URL_PAYMENT_BASE_TBRAINS'
--delete from BODBA.BO_PARAMETROS where NOMBRE='REDIRECT_URL_SUCCESS_TBRAINS'
--delete from BODBA.BO_PARAMETROS where NOMBRE='REDIRECT_URL_ERROR_TBRAINS'

Lista de Errores
1 - Pedido existe, limpiamos capacidades tomadas y se borra el pedido en estado 1
2 - El request del IdPedido es nulo
3 - El estado del IdPedido NO es Pre-Ingresado(1)
4 - Error  de Aplicacion, Ej:null , ERR_CAPACIDAD, JORNADAS
5 - El pedido es nulo, no se pudo rescatar el pedido de la sesion o no se encontro informacion del pedido
6 - Error al ingresar el pago de venta masiva token (BO_VENTAMASIVA_PURCHASE)
7 - Pedido existe, se limpia capacidades tomadas y se borra pedido en estado 1 - TBK, Error no controlado, cuando llaman a cerrar una OP que no
																				// tenga el OK de transbank o que no este preingresado
8 - El estado del pedido no es (1) Pre-ingresaso
9 - Tipo de autorizacion No es 'A'
10 - Faltan parametros minimos
11 - Dispositivo incorrecto, debe ser (M)
12 - Token no encontrado(oc)
13 - Token no encontrado(oc), dto es nulo
14 - Error, 'oc' es nulo,  Caso de excepcion, por alguna razon webpay llama aveces mas de una vez la pagina de exito, en esos casos enviamos a la pagina de resumen
15 - Error al rescatar pedido o recatar token
16 - El pedido es nulo, no se pudo rescatar el pedido de la sesion y tampoco de la url(oc)
17 - Error al ingresar Detalle Picking al sistema.

INSERT INTO BODBA.BO_HORARIO_PICK(/*ID_HOR_PICK*/ ID_SEMANA, ID_LOCAL, HINI, HFIN, N_HORAS) 
	VALUES(567, 4, '09:00:00', '10:00:00', 1)
GO
--SELECT ID_HOR_PICK, ID_SEMANA, ID_LOCAL, HINI, HFIN, N_HORAS FROM BO_HORARIO_PICK WHERE ID_SEMANA = 567

INSERT INTO BODBA.BO_JORNADAS_PICK(/*ID_JPICKING*/ ID_LOCAL, ID_HOR_PICK, ID_SEMANA, ID_ESTADO, DOW, FECHA, CAPAC_PICKING, CAPAC_OCUPADA) 
	VALUES(4, 13141, 567, 10, 0, '2016-7-1', 0, 0)
GO
--SELECT * FROM BO_JORNADAS_PICK WHERE ID_LOCAL = 4 AND ID_HOR_PICK=13141 AND ID_SEMANA = 567

INSERT INTO BODBA.BO_RONDAS(/*ID_RONDA*/ ID_SECTOR, ID_USUARIO, ID_JPICKING, ID_ESTADO, ID_LOCAL, CANT_PRODUCTOS, FINI_PICKING, FFIN_PICKING, ID_USUARIO_FISCAL, FECHA_IMP_LIST_PKL, FECHA_INI_RONDA_PKL, ESTADO_AUDIT_SUSTITUCION) 
	VALUES(28, 1, 84481, 13, 4, 0, '2016-7-1 09:10:00', '2016-7-1 10:00:00', -1, null, null, '')
GO
--SELECT * FROM BO_RONDAS WHERE ID_SECTOR=28 AND ID_USUARIO=1

-- VALIDAR CREAR UNO VIRTUAL ID_PEDIDO
INSERT INTO BODBA.BO_BINS_PEDIDO(/*ID_BP*/ ID_RONDA, ID_PEDIDO, COD_BIN, COD_SELLO1, COD_SELLO2, COD_UBICACION, TIPO) 
	VALUES(1664002, 1213914, '', '', '', '', 'V')
GO
SELECT * FROM BO_BINS_PEDIDO WHERE ID_RONDA = 1664002 AND ID_PEDIDO=1213914


INSERT INTO BODBA.BO_HORARIO_PICK(/*ID_HOR_PICK*/ ID_SEMANA, ID_LOCAL, HINI, HFIN, N_HORAS) 
	VALUES(567, 4, '09:00:00', '10:00:00', 1)
GO
--SELECT ID_HOR_PICK, ID_SEMANA, ID_LOCAL, HINI, HFIN, N_HORAS FROM BO_HORARIO_PICK WHERE ID_SEMANA = 567

INSERT INTO BODBA.BO_JORNADAS_PICK(/*ID_JPICKING*/ ID_LOCAL, ID_HOR_PICK, ID_SEMANA, ID_ESTADO, DOW, FECHA, CAPAC_PICKING, CAPAC_OCUPADA) 
	VALUES(4, 13141, 567, 10, 0, '2016-7-1', 0, 0)
GO
--SELECT * FROM BO_JORNADAS_PICK WHERE ID_LOCAL = 4 AND ID_HOR_PICK=13141 AND ID_SEMANA = 567


INSERT INTO BODBA.BO_RONDAS(/*ID_RONDA*/ ID_SECTOR, ID_USUARIO, ID_JPICKING, ID_ESTADO, ID_LOCAL, CANT_PRODUCTOS, FINI_PICKING, FFIN_PICKING, ID_USUARIO_FISCAL, FECHA_IMP_LIST_PKL, FECHA_INI_RONDA_PKL, ESTADO_AUDIT_SUSTITUCION) 
	VALUES(28, 1, 84481, 13, 4, 0, '2016-7-1 09:10:00', '2016-7-1 10:00:00', -1, null, null, '')
GO
--SELECT * FROM BO_RONDAS WHERE ID_SECTOR=28 AND ID_USUARIO=1

-- VALIDAR CREAR UNO VIRTUAL ID_PEDIDO
INSERT INTO BODBA.BO_BINS_PEDIDO(/*ID_BP*/ ID_RONDA, ID_PEDIDO, COD_BIN, COD_SELLO1, COD_SELLO2, COD_UBICACION, TIPO) 
	VALUES(1664002, 1213914, '', '', '', '', 'V')
GO
--SELECT * FROM BO_BINS_PEDIDO WHERE ID_RONDA = 1664002 AND ID_PEDIDO=1213914

-- insertar id_jpicking del paso anterior
INSERT
INTO bo_pedidos (
		id_estado, id_jdespacho, id_jpicking, id_local, id_local_fact, id_comuna, id_zona
		, id_cliente, genero, fnac, nom_cliente, telefono2, telefono, tipo_despacho
		, costo_despacho, fcreacion, monto_pedido, indicacion, medio_pago, num_mp, fecha_exp
		, n_cuotas, nom_tbancaria, tb_banco, cant_productos, rut_cliente, dv_cliente, dir_id
        , dir_tipo_calle, dir_calle, dir_numero, dir_depto, pol_id, pol_sustitucion, sin_gente_op
        , sin_gente_txt, tipo_doc, id_usuario_fono, observacion, RUT_TIT, DV_TIT, NOM_TIT
        , APAT_TIT, AMAT_TIT, DIR_TIT, DIR_NUM_TIT, CLAVE_MP, DISPOSITIVO, SIN_GENTE_RUT
        , SIN_GENTE_DV, TIPO_PICKING, monto_reservado 
	)
VALUES
	(
		10, 1, 1, 4, 1, 1, 504
        , 000, 'M', NULL, 'vmvinos', '', '', 'N'
        , 0 ,null, 0, '', '', '', ''
        , 0, '', '', 0, 0, '0', 0
        , '', '', '', 0, 0, '', 0
        , '', '', 0, '', '', '', ''
        , '', '', '', '', '', 'B', 0
        , '', 'N', 0
	)
go
select * FROM bodba.BO_PEDIDOS where NOM_CLIENTE='vmvinos'
