INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'URL_PAGO_CAT_TBRAINS', 'http://pagostest.tarjetasmas.cl/BotonDePagoTA/inicio.do' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_TBRAINS', 'http://200.1.131.54/VentaMasiva/PurchasePay' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_PAYMENT_BASE_TBRAINS', 'http://200.1.131.54' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_SUCCESS_TBRAINS', 'http://jumbobf-front.dev.2brains.cl/#/success' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'REDIRECT_URL_ERROR_TBRAINS', 'http://jumbobf-front.dev.2brains.cl/#/error' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'POLIGONO_VENTA_MASIVA', '206' FROM BODBA.BO_PARAMETROS
GO
INSERT INTO BODBA.BO_PARAMETROS (ID_PARAMETRO, NOMBRE, VALOR)
SELECT MAX(ID_PARAMETRO)+1, 'ID_BP_VENTA_MASIVA', '5479472' FROM BODBA.BO_PARAMETROS
GO

--Para registar op y token de pago asociado a venta masiva
CREATE TABLE BODBA.BO_VENTAMASIVA_PURCHASE(
   ID INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
   ID_PEDIDO INTEGER not null,
   TOKEN_PAGO VARCHAR (255),
   ESTADO CHAR(1),
   FCREACION  TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP,
   FVALIDACION  TIMESTAMP,
   CONSTRAINT PK_PAGO_ID PRIMARY KEY (ID)
) IN BO_TABLESPACE
GO

COMMENT ON TABLE BODBA.BO_VENTAMASIVA_PURCHASE IS 'Registro de pago en a traves de la App Venta Masiva.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.ID IS 'Id unico de la tabla.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.ID_PEDIDO IS 'Numero de pedido.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.TOKEN_PAGO IS 'Hash para validar op post ejecucion del servicio de pago seleccionado.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.ESTADO IS 'Estado de pago A: aceptado, R: rechazado.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.FCREACION IS 'Fecha creacion token de validacion.';
COMMENT ON COLUMN BODBA.BO_VENTAMASIVA_PURCHASE.FVALIDACION IS 'Fecha en que se valido el pago. (Cuando cambia el estado)';

-- Generacion de zona de Venta masiva para calendario
INSERT INTO BODBA.BO_ZONAS(ID_LOCAL, NOMBRE, DESCRIPCION, TARIFA_NORMAL_BAJA, TARIFA_NORMAL_MEDIA, TARIFA_NORMAL_ALTA, TARIFA_ECONOMICA, TARIFA_EXPRESS, ESTADO_TARIFA_EXPRESS, ESTADO_TARIFA_ECONOMICA, MENSAJE_CAL_DESPACHO, ORDEN_ZONA, REGALO_CLIENTES, ESTADO_DESCUENTO_CAT, ESTADO_DESCUENTO_TBK, ESTADO_DESCUENTO_PAR, MONTO_DESCUENTO_CAT, MONTO_DESCUENTO_TBK, MONTO_DESCUENTO_PAR, MONTO_DESCUENTO_PC_CAT, MONTO_DESCUENTO_PC_TBK, MONTO_DESCUENTO_PC_PAR) 
	VALUES(1, 'Z99 Venta Masiva', 'Venta Masiva', 990, 990, 990, 990, 990, 0, 0, '', 1000, 1, 3, 3, 3, 120000, 120000, 120000, 50000, 50000, 50000)
GO
INSERT INTO BODBA.BO_POLIGONO(ID_ZONA, ID_COMUNA, NUM_POLIGONO, DESCRIPCION) 
	VALUES( 644, 4, 9999, 'Poligono Venta Masiva')
GO

--actualiza zonas venta masiva
UPDATE bo_zonas SET ID_LOCAL=4  WHERE ID_ZONA=564
update bo_parametros set valor=208 where ID_PARAMETRO=47