*** INFORME DE MODIFICACION DE PRECIOS ***
INSERT INTO BODBA.BO_COMANDOS ( ID_COMANDO, NOMBRE_CLASE, DESCRIPCION, SEGURIDAD, ACTIVO ) VALUES ( 548, 'ViewInformeModPrecios', 'informe Modificacion de Precios [BOC]', 'S', 'A' );
INSERT INTO BODBA.BO_COMXPERF ( ID_COMANDO, ID_PERFIL ) VALUES ( 548, 1 ); 


*** AL ANULAR PEDIDO SE ENVIA ALERTA AL BOC ***
ALTER TABLE BODBA.BO_PEDIDOS ADD ANULAR_BOLETA INTEGER DEFAULT 0;
COMMENT ON COLUMN BODBA.BO_PEDIDOS.ANULAR_BOLETA IS 'Indicador de informar a local la anulacion de boletas';

INSERT INTO BODBA.BO_COMANDOS ( ID_COMANDO, NOMBRE_CLASE, DESCRIPCION, SEGURIDAD, ACTIVO ) VALUES ( 549, 'LiberaAnularBoleta', 'Desmarcar la anulacion de boleta en local  [BOC]', 'S', 'A' );
INSERT INTO BODBA.BO_COMXPERF ( ID_COMANDO, ID_PERFIL ) VALUES ( 549, 1 ); 

*** Los DPC ***
ALTER TABLE BODBA.BO_LOCALES ADD DPC INTEGER DEFAULT 0;
COMMENT ON COLUMN BODBA.BO_LOCALES.DPC IS 'DPC asociado al local fisico';

UPDATE BODBA.BO_LOCALES SET DPC=4815 WHERE ID_LOCAL=1;
UPDATE BODBA.BO_LOCALES SET DPC=4804 WHERE ID_LOCAL=2;
UPDATE BODBA.BO_LOCALES SET DPC=4811 WHERE ID_LOCAL=3;
UPDATE BODBA.BO_LOCALES SET DPC=4812 WHERE ID_LOCAL=4;
UPDATE BODBA.BO_LOCALES SET DPC=4857 WHERE ID_LOCAL=5;
UPDATE BODBA.BO_LOCALES SET DPC=4828 WHERE ID_LOCAL=6;
UPDATE BODBA.BO_LOCALES SET DPC=4834 WHERE ID_LOCAL=7;
UPDATE BODBA.BO_LOCALES SET DPC=4840 WHERE ID_LOCAL=8;

****permisos para ver estadisticas bitacora webpay, fono********
INSERT INTO BODBA.BO_COMANDOS ( ID_COMANDO, NOMBRE_CLASE, DESCRIPCION, SEGURIDAD, ACTIVO ) VALUES ( 550, 'ViewInformeEstadisticasBitWebpay', 'Informe de estadisticas de las bitacoras webpay [BOC]', 'S', 'A');
INSERT INTO BODBA.BO_COMXPERF ( ID_COMANDO, ID_PERFIL ) VALUES ( 550, 1 ); 

*** MODIFICAR CANTIDADES DE PRODUCTOS DE PEDIDO ***
INSERT INTO BODBA.BO_COMANDOS ( ID_COMANDO, NOMBRE_CLASE, DESCRIPCION, SEGURIDAD, ACTIVO ) VALUES ( 551, 'ViewModCantidadProductos', 'Formulario Modificar Cantidad de Productos [BOC]', 'S', 'A' );
INSERT INTO BODBA.BO_COMANDOS ( ID_COMANDO, NOMBRE_CLASE, DESCRIPCION, SEGURIDAD, ACTIVO ) VALUES ( 552, 'ModCantidadProductos', 'Modificar Cantidad de Productos [BOC]', 'S', 'A' );

INSERT INTO BODBA.BO_COMXPERF ( ID_COMANDO, ID_PERFIL ) VALUES ( 551, 1 ); 
INSERT INTO BODBA.BO_COMXPERF ( ID_COMANDO, ID_PERFIL ) VALUES ( 552, 1 );

