--ER/Studio 7.0 SQL Code Generation
-- Company :      CENCOSUD
-- Project :      MONITOR.DM1
-- Author :       IVAN MOYANO


DROP TABLE BO_CHOFER_TRANS;
DROP TABLE BO_EMP_TRANSPORTE;
DROP TABLE BO_FONO_TRANS;
DROP TABLE BO_LOCAL_EMPTRANS;
DROP TABLE BO_LOG_RUTA;
DROP TABLE BO_MOTIVO_DESPACHO;
DROP TABLE BO_PATENTE_TRANS;
DROP TABLE BO_PEDIDOS_EXT;
DROP TABLE BO_RESPONSABLE_DESPACHO;
DROP TABLE BO_RUTA;


CREATE TABLE BO_CHOFER_TRANS(
    ID_CHOFER_TRANS      INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    NOMBRE_CHOFER        VARCHAR(255),
    ACTIVADO             CHAR(1)         WITH DEFAULT 'N',
    ID_EMP_TRANSPORTE    INTEGER,
    CONSTRAINT PK_CHOFER PRIMARY KEY (ID_CHOFER_TRANS)
)
;


-- TABLE: BO_EMP_TRANSPORTE 
CREATE TABLE BO_EMP_TRANSPORTE(
    ID_EMP_TRANSPORTE    INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    NOMBRE_EMPRESA       VARCHAR(255),
    ACTIVADO             CHAR(1)         WITH DEFAULT 'N',
    CONSTRAINT PK_EMPTRANS PRIMARY KEY (ID_EMP_TRANSPORTE)
)
;


-- TABLE: BO_FONO_TRANS 
CREATE TABLE BO_FONO_TRANS(
    ID_FONO_TRANS        INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    CODIGO               INTEGER,
    NUMERO               INTEGER,
    ACTIVADO             CHAR(1)    WITH DEFAULT 'N',
    ID_EMP_TRANSPORTE    INTEGER,
    CONSTRAINT PK_FONTRANS PRIMARY KEY (ID_FONO_TRANS)
)
;

-- TABLE: BO_LOCAL_EMPTRANS 
CREATE TABLE BO_LOCAL_EMPTRANS(
    ID_LOCAL             INTEGER    NOT NULL,
    ID_EMP_TRANSPORTE    INTEGER    NOT NULL,
    CONSTRAINT PK_LOCEMPTR PRIMARY KEY (ID_LOCAL, ID_EMP_TRANSPORTE)
)
;

-- TABLE: BO_LOG_RUTA 
CREATE TABLE BO_LOG_RUTA(
    ID_LOG_RUTA    INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    ID_RUTA        INTEGER         NOT NULL,
    FECHA          TIMESTAMP,
    DESCRIPCION    VARCHAR(300),
    ID_USUARIO     INTEGER,
    CONSTRAINT PK_LOG_RUTA PRIMARY KEY (ID_LOG_RUTA, ID_RUTA)
)
;

-- TABLE: BO_MOTIVO_DESPACHO 
CREATE TABLE BO_MOTIVO_DESPACHO(
    ID_MOTIVO_DESP    INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    MOTIVO            VARCHAR(255),
    ACTIVADO          CHAR(1)         WITH DEFAULT 'N',
    CONSTRAINT PK_MOTDESP PRIMARY KEY (ID_MOTIVO_DESP)
)
;

-- TABLE: BO_PATENTE_TRANS 
CREATE TABLE BO_PATENTE_TRANS(
    ID_PATENTE_TRANS     INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    PATENTE              VARCHAR(30),
    ACTIVADO             CHAR(1)       WITH DEFAULT 'N',
    CANT_MAX_BINS        INTEGER,
    ID_EMP_TRANSPORTE    INTEGER,
    CONSTRAINT PK_PATENTE PRIMARY KEY (ID_PATENTE_TRANS)
)
;

-- TABLE: BO_PEDIDOS_EXT 
CREATE TABLE BO_PEDIDOS_EXT(
    ID_PEDIDO                 INTEGER      NOT NULL,
    TIPO_PEDIDO               CHAR(1)      WITH DEFAULT 'J',
    NRO_GUIA_CASO             INTEGER,
    FECHA_HORA_LLEGADA_DOM    TIMESTAMP,
    FECHA_HORA_SALIDA_DOM     TIMESTAMP,
    ATRASADA                  CHAR(1)	   WITH DEFAULT 'N',	
    REPROGRAMADA              CHAR(1)      WITH DEFAULT 'N',
    ID_MOTIVO_DESP            INTEGER,
    ID_RESPONSABLE_DESP       INTEGER,
    ID_RUTA                   INTEGER,
    CONSTRAINT PK_PEDEXTRA PRIMARY KEY (ID_PEDIDO)
)
;

-- TABLE: BO_RESPONSABLE_DESPACHO 
CREATE TABLE BO_RESPONSABLE_DESPACHO(
    ID_RESPONSABLE_DESP    INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    NOMBRE_RESPONSABLE     VARCHAR(255),
    ACTIVADO               CHAR(1)         WITH DEFAULT 'N',
    CONSTRAINT PK_RESPDESP PRIMARY KEY (ID_RESPONSABLE_DESP)
)
;

-- TABLE: BO_RUTA 
CREATE TABLE BO_RUTA(
    ID_RUTA              INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    ID_FONO_TRANS        INTEGER,
    ID_CHOFER_TRANS      INTEGER,
    ID_PATENTE_TRANS     INTEGER,
    FECHA_HORA_SALIDA    TIMESTAMP,
    FECHA_CREACION       TIMESTAMP,
    ID_ESTADO            INTEGER,
    CONSTRAINT PK_RUTA PRIMARY KEY (ID_RUTA)
)
;


-- INDEX: Ref834 
CREATE INDEX Ref834 ON BO_CHOFER_TRANS(ID_EMP_TRANSPORTE);

-- INDEX: Ref833 
CREATE INDEX Ref833 ON BO_FONO_TRANS(ID_EMP_TRANSPORTE);

-- INDEX: Ref1937 
CREATE INDEX Ref1937 ON BO_LOCAL_EMPTRANS(ID_LOCAL);

-- INDEX: Ref838 
CREATE INDEX Ref838 ON BO_LOCAL_EMPTRANS(ID_EMP_TRANSPORTE);

-- INDEX: Ref317 
CREATE INDEX Ref317 ON BO_LOG_RUTA(ID_RUTA);

-- INDEX: Ref1732 
CREATE INDEX Ref1732 ON BO_LOG_RUTA(ID_USUARIO);

-- INDEX: Ref81 
CREATE INDEX Ref81 ON BO_PATENTE_TRANS(ID_EMP_TRANSPORTE);

-- INDEX: Ref1022 
CREATE INDEX Ref1022 ON BO_PEDIDOS_EXT(ID_MOTIVO_DESP);

-- INDEX: Ref923 
CREATE INDEX Ref923 ON BO_PEDIDOS_EXT(ID_RESPONSABLE_DESP);

-- INDEX: Ref125 ERROR
CREATE INDEX Ref125 ON BO_PEDIDOS_EXT(ID_PEDIDO);

-- INDEX: Ref326
CREATE INDEX Ref326 ON BO_PEDIDOS_EXT(ID_RUTA);

-- INDEX: Ref62
CREATE INDEX Ref62 ON BO_RUTA(ID_FONO_TRANS);

-- INDEX: Ref53 
CREATE INDEX Ref53 ON BO_RUTA(ID_CHOFER_TRANS);

-- INDEX: Ref74 
CREATE INDEX Ref74 ON BO_RUTA(ID_PATENTE_TRANS);

-- INDEX: Ref1412 
CREATE INDEX Ref1412 ON BO_RUTA(ID_ESTADO);



-- TABLE: BO_CHOFER_TRANS 
ALTER TABLE BO_CHOFER_TRANS ADD CONSTRAINT RefCHOF_EMPTRANS 
    FOREIGN KEY (ID_EMP_TRANSPORTE)
    REFERENCES BO_EMP_TRANSPORTE(ID_EMP_TRANSPORTE)
;

-- TABLE: BO_FONO_TRANS 
ALTER TABLE BO_FONO_TRANS ADD CONSTRAINT RefFONO_EMPTRANS 
    FOREIGN KEY (ID_EMP_TRANSPORTE)
    REFERENCES BO_EMP_TRANSPORTE(ID_EMP_TRANSPORTE)
;

-- TABLE: BO_LOCAL_EMPTRANS 
ALTER TABLE BO_LOCAL_EMPTRANS ADD CONSTRAINT RefLOC_EMPTRANS1
    FOREIGN KEY (ID_LOCAL)
    REFERENCES BO_LOCALES(ID_LOCAL)
;
ALTER TABLE BO_LOCAL_EMPTRANS ADD CONSTRAINT RefLOC_EMPTRANS2 
    FOREIGN KEY (ID_EMP_TRANSPORTE)
    REFERENCES BO_EMP_TRANSPORTE(ID_EMP_TRANSPORTE)
;


-- TABLE: BO_LOG_RUTA 
ALTER TABLE BO_LOG_RUTA ADD CONSTRAINT RefLOGRUTA_RUTA 
    FOREIGN KEY (ID_RUTA)
    REFERENCES BO_RUTA(ID_RUTA)
;
ALTER TABLE BO_LOG_RUTA ADD CONSTRAINT RefLOGRUTA_USU 
    FOREIGN KEY (ID_USUARIO)
    REFERENCES BO_USUARIOS(ID_USUARIO)
;


-- TABLE: BO_PATENTE_TRANS 
ALTER TABLE BO_PATENTE_TRANS ADD CONSTRAINT RefPAT_EMPTRANS 
    FOREIGN KEY (ID_EMP_TRANSPORTE)
    REFERENCES BO_EMP_TRANSPORTE(ID_EMP_TRANSPORTE)
;

-- TABLE: BO_PEDIDOS_EXT 
ALTER TABLE BO_PEDIDOS_EXT ADD CONSTRAINT RefPEDEXT_MOT 
    FOREIGN KEY (ID_MOTIVO_DESP)
    REFERENCES BO_MOTIVO_DESPACHO(ID_MOTIVO_DESP)
;
ALTER TABLE BO_PEDIDOS_EXT ADD CONSTRAINT RefPEDEXT_RESP 
    FOREIGN KEY (ID_RESPONSABLE_DESP)
    REFERENCES BO_RESPONSABLE_DESPACHO(ID_RESPONSABLE_DESP)
;
ALTER TABLE BO_PEDIDOS_EXT ADD CONSTRAINT RefPEDEXT_PED 
    FOREIGN KEY (ID_PEDIDO)
    REFERENCES BO_PEDIDOS(ID_PEDIDO)
;
ALTER TABLE BO_PEDIDOS_EXT ADD CONSTRAINT RefPEDEXT_RUTA 
    FOREIGN KEY (ID_RUTA)
    REFERENCES BO_RUTA(ID_RUTA)
;

-- TABLE: BO_RUTA 
ALTER TABLE BO_RUTA ADD CONSTRAINT RefRUTA_FONOTRANS 
    FOREIGN KEY (ID_FONO_TRANS)
    REFERENCES BO_FONO_TRANS(ID_FONO_TRANS)
;
ALTER TABLE BO_RUTA ADD CONSTRAINT RefRUTA_CHOFER 
    FOREIGN KEY (ID_CHOFER_TRANS)
    REFERENCES BO_CHOFER_TRANS(ID_CHOFER_TRANS)
;
ALTER TABLE BO_RUTA ADD CONSTRAINT RefRUTA_PATENTE 
    FOREIGN KEY (ID_PATENTE_TRANS)
    REFERENCES BO_PATENTE_TRANS(ID_PATENTE_TRANS)
;
ALTER TABLE BO_RUTA ADD CONSTRAINT RefRUTA_ESTADO 
    FOREIGN KEY (ID_ESTADO)
    REFERENCES BO_ESTADOS(ID_ESTADO)
;


/*
-- TABLE: BO_COMUNAS 
CREATE TABLE BO_COMUNAS(
    ID_COMUNA    INTEGER    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (ID_COMUNA)
)
;
-- TABLE: BO_ESTADOS 
CREATE TABLE BO_ESTADOS(
    ID_ESTADO    INTEGER    NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (ID_ESTADO)
)
;
-- TABLE: BO_JORNADA_DESP 
CREATE TABLE BO_JORNADA_DESP(
    ID_JDESPACHO    INTEGER    NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (ID_JDESPACHO)
)
;
-- TABLE: BO_LOCALES 
CREATE TABLE BO_LOCALES(
    ID_LOCAL    INTEGER    NOT NULL,
    CONSTRAINT PK19 PRIMARY KEY (ID_LOCAL)
)
;
-- TABLE: BO_PEDIDOS 
CREATE TABLE BO_PEDIDOS(
    ID_PEDIDO       INTEGER    NOT NULL,
    ID_ESTADO       INTEGER,
    ID_JDESPACHO    INTEGER,
    ID_COMUNA       INTEGER,
    ID_ZONA         INTEGER,
    CONSTRAINT PK1 PRIMARY KEY (ID_PEDIDO)
)
;
-- TABLE: BO_USUARIOS 
CREATE TABLE BO_USUARIOS(
    ID_USUARIO    INTEGER    NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (ID_USUARIO)
)
;
-- TABLE: BO_ZONAS 
CREATE TABLE BO_ZONAS(
    ID_ZONA    INTEGER    NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (ID_ZONA)
)
;
*/

/*
-- INDEX: Ref1418 
CREATE INDEX Ref1418 ON BO_PEDIDOS(ID_ESTADO);
-- INDEX: Ref1219 
CREATE INDEX Ref1219 ON BO_PEDIDOS(ID_JDESPACHO);
-- INDEX: Ref1120 
CREATE INDEX Ref1120 ON BO_PEDIDOS(ID_COMUNA);
-- INDEX: Ref1321 
CREATE INDEX Ref1321 ON BO_PEDIDOS(ID_ZONA);
*/

/*
-- TABLE: BO_PEDIDOS 
ALTER TABLE BO_PEDIDOS ADD CONSTRAINT RefBO_ESTADOS18 
    FOREIGN KEY (ID_ESTADO)
    REFERENCES BO_ESTADOS(ID_ESTADO)
;

ALTER TABLE BO_PEDIDOS ADD CONSTRAINT RefBO_JORNADA_DESP19 
    FOREIGN KEY (ID_JDESPACHO)
    REFERENCES BO_JORNADA_DESP(ID_JDESPACHO)
;

ALTER TABLE BO_PEDIDOS ADD CONSTRAINT RefBO_COMUNAS20 
    FOREIGN KEY (ID_COMUNA)
    REFERENCES BO_COMUNAS(ID_COMUNA)
;

ALTER TABLE BO_PEDIDOS ADD CONSTRAINT RefBO_ZONAS21 
    FOREIGN KEY (ID_ZONA)
    REFERENCES BO_ZONAS(ID_ZONA)
;
*/


ALTER TABLE BODBA.BO_PEDIDOS_EXT ADD MAIL VARCHAR(50) 
;
ALTER TABLE BODBA.BO_FONO_TRANS ADD NOMBRE VARCHAR(20) 
;
ALTER TABLE BODBA.BO_PEDIDOS_EXT ADD BINS_DESC VARCHAR(300) 
;
ALTER TABLE BODBA.BO_PEDIDOS_EXT ADD TIPO_JUMBO_VA VARCHAR(1) 
;
COMMENT ON COLUMN BODBA.BO_PEDIDOS_EXT.TIPO_JUMBO_VA IS
'Aplica para JumboVA: D=Despacho C=Caso JumboVA'
;

ALTER TABLE BODBA.BO_LOG_RUTA ADD ID_ESTADO INTEGER 
;
ALTER TABLE BODBA.BO_LOG_RUTA ADD CONSTRAINT REFLOGRUTA_EST
FOREIGN KEY (ID_ESTADO)
REFERENCES BODBA.BO_ESTADOS (ID_ESTADO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;

ALTER TABLE BODBA.BO_RUTA ADD ID_LOCAL INTEGER 
;
ALTER TABLE BODBA.BO_RUTA ADD CONSTRAINT REFRUTA_LOCAL
FOREIGN KEY (ID_LOCAL)
REFERENCES BODBA.BO_LOCALES (ID_LOCAL)
ON DELETE NO ACTION
ON UPDATE NO ACTION
;

ALTER TABLE BODBA.BO_RUTA ADD CANT_BINS INTEGER 
;

ALTER TABLE BODBA.BO_PEDIDOS_EXT ADD VECES_EN_RUTA INTEGER DEFAULT 0
;
COMMENT ON COLUMN BODBA.BO_PEDIDOS_EXT.VECES_EN_RUTA IS
'Cantidad de veces que a estado en transito'
;

ALTER TABLE BODBA.BO_PEDIDOS_EXT ADD "ID_JDESPACHO_ORI" INTEGER 
;
COMMENT ON COLUMN BODBA.BO_PEDIDOS_EXT."ID_JDESPACHO_ORI" IS
'Jornada despacho original (historial) en caso de reprogramacion'
;

COMMENT ON COLUMN BODBA.BO_PEDIDOS_EXT."ATRASADA" IS
'S=Si o N=No'
;
COMMENT ON COLUMN BODBA.BO_PEDIDOS_EXT."REPROGRAMADA" IS
'S=Si o N=No'
;

ALTER TABLE BODBA.BO_PEDIDOS_EXT ADD CON_DEVOLUCION CHARACTER(1) DEFAULT 'N'
;
COMMENT ON COLUMN BODBA.BO_PEDIDOS_EXT.CON_DEVOLUCION IS
'S=Si o N=No'
;



INSERT INTO BODBA.BO_ESTADOS ( ID_ESTADO, TIPO_ESTADO, NOMBRE ) VALUES ( 65, 'RU', 'En Preparación' ); 
INSERT INTO BODBA.BO_ESTADOS ( ID_ESTADO, TIPO_ESTADO, NOMBRE ) VALUES ( 66, 'RU', 'En Ruta' );
INSERT INTO BODBA.BO_ESTADOS ( ID_ESTADO, TIPO_ESTADO, NOMBRE ) VALUES ( 67, 'RU', 'Finalizada' ); 
INSERT INTO BODBA.BO_ESTADOS ( ID_ESTADO, TIPO_ESTADO, NOMBRE ) VALUES ( 68, 'RU', 'Con Reprogramación' );
INSERT INTO BODBA.BO_ESTADOS ( ID_ESTADO, TIPO_ESTADO, NOMBRE ) VALUES ( 69, 'RU', 'Anulada' );

